name: "webmin.dev: webmin/usermin"

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: webmin/webmin-ci-cd/.github/workflows/testing-master-workflow.yml@main
    with:
      build-type: package
      project-name: usermin
